# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2
before:
  hooks:
    - go mod tidy
    - go generate ./...
    - ./scripts/completion.sh

builds:
  - env:
      - CGO_ENABLED=0
    binary: heyframe-cli
    ldflags: -s -w -X 'github.com/heyframe/heyframe-cli/cmd.version={{ .Version }}'
    flags:
      - -trimpath
    goos:
      - linux
      - darwin
    ignore:
      - goos: linux
        goarch: '386'

archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    files:
      - LICENSE
      - completions/*

release:
  github:
    owner: heyframe
    name: heyframe-cli

dockers:
  - image_templates:
      - "heyframe/heyframe-cli:{{ .Version }}-php-8.4"
      - "heyframe/heyframe-cli:latest-php-8.4"
      - "ghcr.io/heyframe/heyframe-cli:{{ .Version }}-php-8.4"
      - "ghcr.io/heyframe/heyframe-cli:latest-php-8.4"
    dockerfile: Dockerfile
    goos: linux
    goarch:
      - amd64
      - arm64
    build_flag_templates:
      - "--build-arg=PHP_VERSION=8.4"

  - image_templates:
      - "heyframe/heyframe-cli:{{ .Version }}-php-8.3"
      - "heyframe/heyframe-cli:latest-php-8.3"
      - "heyframe/heyframe-cli:{{ .Version }}"
      - "heyframe/heyframe-cli:latest"
      - "ghcr.io/heyframe/heyframe-cli:{{ .Version }}-php-8.3"
      - "ghcr.io/heyframe/heyframe-cli:latest-php-8.3"
      - "ghcr.io/heyframe/heyframe-cli:{{ .Version }}"
      - "ghcr.io/heyframe/heyframe-cli:latest"
    dockerfile: Dockerfile
    goos: linux
    goarch:
      - amd64
      - arm64
    build_flag_templates:
      - "--build-arg=PHP_VERSION=8.3"

  - image_templates:
      - "heyframe/heyframe-cli:{{ .Version }}-php-8.2"
      - "heyframe/heyframe-cli:latest-php-8.2"
      - "ghcr.io/heyframe/heyframe-cli:{{ .Version }}-php-8.2"
      - "ghcr.io/heyframe/heyframe-cli:latest-php-8.2"
    dockerfile: Dockerfile
    goos: linux
    goarch:
      - amd64
      - arm64
    build_flag_templates:
      - "--build-arg=PHP_VERSION=8.2"

  - image_templates:
      - "heyframe/heyframe-cli:{{ .Version }}-php-8.1"
      - "heyframe/heyframe-cli:latest-php-8.1"
      - "ghcr.io/heyframe/heyframe-cli:{{ .Version }}-php-8.1"
      - "ghcr.io/heyframe/heyframe-cli:latest-php-8.1"
    dockerfile: Dockerfile
    goos: linux
    goarch:
      - amd64
      - arm64
    build_flag_templates:
      - "--build-arg=PHP_VERSION=8.1"

  - image_templates:
      - "heyframe/heyframe-cli:bin-{{ .Version }}"
      - "heyframe/heyframe-cli:bin"
      - "ghcr.io/heyframe/heyframe-cli:bin-{{ .Version }}"
      - "ghcr.io/heyframe/heyframe-cli:bin"
    dockerfile: Dockerfile.bin
    goos: linux
    goarch:
      - amd64
      - arm64

sboms:
  - artifacts: archive
  - id: source
    artifacts: source

signs:
  - cmd: cosign
    certificate: "${artifact}.pem"
    env:
      - COSIGN_EXPERIMENTAL=1
    artifacts: checksum
    args:
      - "sign-blob"
      - "--output-certificate=${certificate}"
      - "--output-signature=${signature}"
      - '${artifact}'
      - "--yes"

docker_signs:
  - cmd: cosign
    env:
      - COSIGN_EXPERIMENTAL=1
    artifacts: all
    args:
      - 'sign'
      - '${artifact}'
      - "--yes"

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^Merge pull request:'
  groups:
    - title: 🚀 Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: "🐛 Bug Fixes"
      regexp: '^.*?bug(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: 🧰 Maintenance
      order: 999
